# Generated by Django 3.0.3 on 2020-02-18 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('L', 'Лекция'), ('P', 'Практика'), ('LB', 'Лаб. работа')], default='L', max_length=2)),
                ('prof_type', models.CharField(choices=[('S', 'Обычная'), ('C', 'Компьютерная'), ('D', 'Дизайн'), ('L', 'Лаборатория'), ('M', 'Мастерская')], default='S', max_length=1)),
                ('need_projector', models.BooleanField()),
                ('need_big_blackboard', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LectureHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spaciousness', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('building', models.CharField(choices=[('V', 'ул. Павла Корчагина'), ('A', 'ул. Автозаводская'), ('E', 'ул. Большая Семеновская'), ('P', 'ул. Прянишникова'), ('S', 'ул. Садовая-Спасская')], default='E', max_length=1)),
                ('prof_type', models.CharField(choices=[('S', 'Обычная'), ('C', 'Компьютерная'), ('D', 'Дизайн'), ('L', 'Лаборатория'), ('M', 'Мастерская')], default='S', max_length=1)),
                ('has_projector', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('B', 'Бакалавриат'), ('S', 'Специалитет'), ('M', 'Магистратура')], default='B', max_length=1)),
                ('constraints', models.TextField(verbose_name='Ограничения направления')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('constraints', models.TextField()),
                ('building', models.CharField(choices=[('V', 'ул. Павла Корчагина'), ('A', 'ул. Автозаводская'), ('E', 'ул. Большая Семеновская'), ('P', 'ул. Прянишникова'), ('S', 'ул. Садовая-Спасская')], default='E', max_length=1)),
                ('disciplines', models.ManyToManyField(to='index.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('count_of_students', models.IntegerField()),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Flow')),
                ('training_direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.TrainingDirection')),
            ],
        ),
    ]
