# Generated by Django 2.0.5 on 2020-04-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200315_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdirection',
            name='constraints',
            field=models.TextField(default='{"buildings": ["E", "A", "P", "V", "S"], "day_constraints": {"MO": [true, true, true, true, true, true, true], "TU": [true, true, true, true, true, true, true], "WE": [true, true, true, true, true, true, true], "TH": [true, true, true, true, true, true, true], "FR": [true, true, true, true, true, true, true], "SA": [true, true, true, true, true, true, true]}}', verbose_name='Ограничения направления'),
        ),
    ]
