# Generated by Django 3.0.3 on 2020-06-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200603_1252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('teacher', 'lesson', 'day_of_week'), ('group', 'lesson', 'day_of_week')},
        ),
    ]
