# Generated by Django 3.0.3 on 2020-05-31 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200427_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='index.Discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='index.Teacher')),
            ],
            options={
                'unique_together': {('discipline', 'teacher')},
            },
        ),
        migrations.AlterField(
            model_name='teacher',
            name='disciplines',
            field=models.ManyToManyField(through='index.TeacherDetails', to='index.Discipline'),
        ),
    ]
